# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c40eafddd11bdba6dacb6b8fad731ad4b0b078218d948a3c699d593ed33809b3246a7fa6db6448bd4ab63d3f174c37dd6befd5d1ae189fa00cfae03a4618b5f3
  dt_email_id: tk1@digitaltown.com
  dt_password: )$dGls*3Ijlk
  sender_wallet_id: 1024
  sender_user_id: 7390
  sender_uu_id: 542c41d4-4fee-11e8-880d-0a3db7c9f7d2
test:
  secret_key_base: c223ec2671e65f94b4dc0d93a9c4f9c2fded1dbdd64d402f446473be302410bd9a43eb220d0b28ee6bc2e8d42465792f8d98e6b74647f2168fdb28a7caca61ae
  dt_email_id: tk1@digitaltown.com
  dt_password: )$dGls*3Ijlk
  sender_wallet_id: 1024
  sender_user_id: 7390
  sender_uu_id: 542c41d4-4fee-11e8-880d-0a3db7c9f7d2
# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  dt_email_id: tk1@digitaltown.com
  dt_password: )$dGls*3Ijlk
  sender_wallet_id: 1024
  sender_user_id: 7390
  sender_uu_id: 542c41d4-4fee-11e8-880d-0a3db7c9f7d2
